language: node_js
node_js: node
jobs:
  include:
    - stage: Test
      install: npm install && npm run bootstrap
      script:
        - npm run test
        - yarn size
    - stage: Build
      install: npm install && npm run bootstrap
      script:
        - npm run build