language: node_js
node_js: node
branches:
  only:
    - master
jobs:
  include:
    - stage: Test
      install: npm install
      # bootstrap: npm run bootstrap
      script:
        - cd packages/launcher && npm run test -- --collectCoverage && npm run codecov
    - stage: Build
      install: npm install
      # bootstrap: npm run bootstrap
      script:
        - cd packages/launcher && npm run build