name: lint

on:
  # push:
  #   branches:
  #     - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: lint check
    runs-on: ubuntu-latest
    
    steps: 
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: install dep
        run: npm ci
      
      - name: run lint
        run: npm run lint