name: Tests

on:
  # push:
  #   branches:
  #     - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    steps: 
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: install dep
        run: npm ci
      
      # - name: bootstrap
      #   run: npm run bootstrap
      
      - name: run test
        run: npm run test